### ISSUE TITLE
Validate options

### ISSUE THREAD

**Issue by peteruithoven** [rspective/voucherify-nodejs-sdk#44]
We had the following server side error: 
```
2016-11-04T14:10:20.900637+00:00 app[web.1]: Error: "value" required in setHeader("X-App-Id", value)
2016-11-04T14:10:20.900638+00:00 app[web.1]:     at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
2016-11-04T14:10:20.900639+00:00 app[web.1]:     at new ClientRequest (_http_client.js:85:14)
2016-11-04T14:10:20.900640+00:00 app[web.1]:     at Object.exports.request (http.js:31:10)
2016-11-04T14:10:20.900640+00:00 app[web.1]:     at Object.exports.request (https.js:199:15)
2016-11-04T14:10:20.900642+00:00 app[web.1]:     at Request.start (/app/node_modules/voucherify/node_modules/request/request.js:946:30)
2016-11-04T14:10:20.900642+00:00 app[web.1]:     at Request.write (/app/node_modules/voucherify/node_modules/request/request.js:1504:10)
2016-11-04T14:10:20.900646+00:00 app[web.1]:     at Immediate._onImmediate (/app/node_modules/voucherify/node_modules/request/request.js:731:7)
2016-11-04T14:10:20.900643+00:00 app[web.1]:     at end (/app/node_modules/voucherify/node_modules/request/request.js:707:16)
2016-11-04T14:10:20.900646+00:00 app[web.1]:     at tryOnImmediate (timers.js:543:15)
2016-11-04T14:10:20.900647+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:523:5)
```
Which took me a while to realise what was happening. 
We initiate Voucherify like this: 
``` js
const voucherify = voucherifyClient({
  applicationId: process.env.VOUCHERIFY_APP_ID,
  clientSecretKey: process.env.VOUCHERIFY_CLIENT_SECRET_KEY
});
```
Basically we forgot to copy our environment variables to Heroku. 

Could the[ `options` given to Voucherify](https://github.com/rspective/voucherify-nodejs-sdk/blob/master/voucherify.js#L10) be validated? This would make mistakes like these much easier to track down.

**Comment by LukaszWiktor** [comment]
Definitely, it's a good idea! We'll improve it soon. Thanks for reporting it.

**Comment by tpindel** [comment]
@peteruithoven Fix provided by @LukaszWiktor has been released. The newest version you will find [in NPM repository](https://www.npmjs.com/package/voucherify).

**Comment by peteruithoven** [comment]
Awesome! Thanks @LukaszWiktor.
